"""add command language to users and enrollments

Revision ID: 00b5eb9e7a73
Revises: 0ebe1d97df58
Create Date: 2026-09-01 09:37:06.232445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b5eb9e7a73'
down_revision: Union[str, Sequence[str], None] = '0ebe1d97df58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command_enrollments', sa.Column('language', sa.String(length=2), server_default='si', nullable=False))
    op.drop_constraint(op.f('uq_command_enrollments_slot'), 'command_enrollments', type_='unique')
    op.create_unique_constraint('uq_command_enrollments_slot', 'command_enrollments', ['user_id', 'command_id', 'language', 'sample_index'])
    op.create_check_constraint('ck_command_enrollments_language', 'command_enrollments', "language IN ('si', 'en')")
    op.add_column('users', sa.Column('command_language', sa.String(length=2), server_default=sa.text("'si'"), nullable=False))
    op.create_check_constraint('ck_users_command_language', 'users', "command_language IN ('si', 'en')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_command_language', 'users', type_='check')
    op.drop_column('users', 'command_language')
    op.drop_constraint('ck_command_enrollments_language', 'command_enrollments', type_='check')
    op.drop_constraint('uq_command_enrollments_slot', 'command_enrollments', type_='unique')
    op.create_unique_constraint(op.f('uq_command_enrollments_slot'), 'command_enrollments', ['user_id', 'command_id', 'sample_index'], postgresql_nulls_not_distinct=False)
    op.drop_column('command_enrollments', 'language')
    # ### end Alembic commands ###
