"""add command_enrollments table

Revision ID: 0ebe1d97df58
Revises: db1607a6a346
Create Date: 2026-08-30 22:06:49.732885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebe1d97df58'
down_revision: Union[str, Sequence[str], None] = 'db1607a6a346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_enrollments',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('embedding_dim > 0', name='ck_command_enrollments_embedding_dim'),
    sa.CheckConstraint('sample_index >= 0', name='ck_command_enrollments_sample_index'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('user_id', 'command_id', 'sample_index', name='uq_command_enrollments_slot')
    )
    op.create_index(op.f('ix_command_enrollments_command_id'), 'command_enrollments', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_enrollments_user_id'), 'command_enrollments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_enrollments_user_id'), table_name='command_enrollments')
    op.drop_index(op.f('ix_command_enrollments_command_id'), table_name='command_enrollments')
    op.drop_table('command_enrollments')
    # ### end Alembic commands ###
