"""add transcription request details

Revision ID: cff062267e37
Revises: f4179b6e7a51
Create Date: 2026-08-06 09:35:02.450097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff062267e37'
down_revision: Union[str, Sequence[str], None] = 'f4179b6e7a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_jobs', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('transcription_jobs', sa.Column('transcript_type', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
    "ck_transcription_jobs_type",
    "transcription_jobs",
    "transcript_type IN ('LECTURE', 'NOTE', 'QUIZ_ANSWER')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_jobs', 'transcript_type')
    op.drop_column('transcription_jobs', 'title')
    # ### end Alembic commands ###
