"""add source column to transcripts for live streaming

Revision ID: db1607a6a346
Revises: cff062267e37
Create Date: 2026-08-28 23:28:40.526423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1607a6a346'
down_revision: Union[str, Sequence[str], None] = 'cff062267e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('source', sa.String(length=20), nullable=True))
    op.create_check_constraint('ck_transcripts_source', 'transcripts', "source IS NULL OR source IN ('UPLOAD', 'LIVE')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_transcripts_source', 'transcripts', type_='check')
    op.drop_column('transcripts', 'source')
    # ### end Alembic commands ###
