"""create initial schema

Revision ID: f4179b6e7a51
Revises: 
Create Date: 2026-08-05 10:51:49.888807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4179b6e7a51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("role IN ('STUDENT', 'TEACHER')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('media_files',
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_media_files_duration'),
    sa.CheckConstraint('file_size >= 0', name='ck_media_files_file_size'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('media_id'),
    sa.UniqueConstraint('storage_path', name='uq_media_files_storage_path')
    )
    op.create_index(op.f('ix_media_files_owner_id'), 'media_files', ['owner_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'CLOSED')", name='ck_quizzes_status'),
    sa.CheckConstraint('available_until IS NULL OR available_from IS NULL OR available_until > available_from', name='ck_quizzes_availability'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_quizzes_created_by'), 'quizzes', ['created_by'], unique=False)
    op.create_index(op.f('ix_quizzes_status'), 'quizzes', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('question_order >= 1', name='ck_questions_order'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('quiz_id', 'question_order', name='uq_questions_order')
    )
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_table('quiz_submissions',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'IN_PROGRESS'"), nullable=False),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('IN_PROGRESS', 'SUBMITTED', 'REVIEWED')", name='ck_quiz_submissions_status'),
    sa.CheckConstraint('mark IS NULL OR (mark >= 0 AND mark <= 100)', name='ck_quiz_submissions_mark'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('quiz_id', 'student_id', name='uq_quiz_submissions_student')
    )
    op.create_index(op.f('ix_quiz_submissions_quiz_id'), 'quiz_submissions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_reviewed_by'), 'quiz_submissions', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_status'), 'quiz_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_student_id'), 'quiz_submissions', ['student_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('transcript_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'FINALIZED')", name='ck_transcripts_status'),
    sa.CheckConstraint("transcript_type IN ('LECTURE', 'NOTE', 'QUIZ_ANSWER')", name='ck_transcripts_type'),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.media_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transcript_id')
    )
    op.create_index(op.f('ix_transcripts_media_id'), 'transcripts', ['media_id'], unique=False)
    op.create_index(op.f('ix_transcripts_owner_id'), 'transcripts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_transcripts_status'), 'transcripts', ['status'], unique=False)
    op.create_table('answer_submissions',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('transcription_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'NOT_STARTED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('NOT_STARTED', 'PROCESSING', 'COMPLETED', 'FAILED')", name='ck_answer_submissions_status'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['quiz_submissions.submission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcripts.transcript_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('answer_id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_answer_submissions_question'),
    sa.UniqueConstraint('transcription_id', name='uq_answer_submissions_transcription')
    )
    op.create_index(op.f('ix_answer_submissions_question_id'), 'answer_submissions', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_submissions_submission_id'), 'answer_submissions', ['submission_id'], unique=False)
    op.create_table('export_records',
    sa.Column('export_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('export_format', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("export_format IN ('TXT', 'DOCX', 'PDF')", name='ck_export_records_format'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.transcript_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_index(op.f('ix_export_records_requested_by'), 'export_records', ['requested_by'], unique=False)
    op.create_index(op.f('ix_export_records_transcript_id'), 'export_records', ['transcript_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('word_metadata', sa.JSON(), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_transcript_segments_confidence'),
    sa.CheckConstraint('end_time >= start_time', name='ck_transcript_segments_time_range'),
    sa.CheckConstraint('segment_order >= 0', name='ck_transcript_segments_order'),
    sa.CheckConstraint('start_time >= 0', name='ck_transcript_segments_start_time'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.transcript_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id'),
    sa.UniqueConstraint('transcript_id', 'segment_order', name='uq_transcript_segments_order')
    )
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_table('transcription_jobs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('progress_percent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('UPLOADING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED')", name='ck_transcription_jobs_status'),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_transcription_jobs_progress'),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.media_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.transcript_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('transcript_id', name='uq_transcription_jobs_transcript_id')
    )
    op.create_index(op.f('ix_transcription_jobs_media_id'), 'transcription_jobs', ['media_id'], unique=False)
    op.create_index(op.f('ix_transcription_jobs_requested_by'), 'transcription_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_transcription_jobs_status'), 'transcription_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcription_jobs_status'), table_name='transcription_jobs')
    op.drop_index(op.f('ix_transcription_jobs_requested_by'), table_name='transcription_jobs')
    op.drop_index(op.f('ix_transcription_jobs_media_id'), table_name='transcription_jobs')
    op.drop_table('transcription_jobs')
    op.drop_index(op.f('ix_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_export_records_transcript_id'), table_name='export_records')
    op.drop_index(op.f('ix_export_records_requested_by'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_answer_submissions_submission_id'), table_name='answer_submissions')
    op.drop_index(op.f('ix_answer_submissions_question_id'), table_name='answer_submissions')
    op.drop_table('answer_submissions')
    op.drop_index(op.f('ix_transcripts_status'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_owner_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_media_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_quiz_submissions_student_id'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_status'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_reviewed_by'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_quiz_id'), table_name='quiz_submissions')
    op.drop_table('quiz_submissions')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_quizzes_status'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_created_by'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_media_files_owner_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
