import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api } from '../api'
import Icon from '../components/Icon'
import { Alert, EmptyState, Loading, PageHeader, StatusBadge } from '../components/UI'
import { useToast } from '../contexts/ToastContext'

export function SubmissionsPage() {
  const [items, setItems] = useState(null); const [error, setError] = useState('')
  useEffect(() => { api.getSubmissions().then(setItems).catch((cause) => setError(cause.message)) }, [])
  return <div className="page"><PageHeader eyebrow="Teacher workspace" title="Review submissions" description="Read transcribed spoken answers and give students clear feedback." />{error && <Alert>{error}</Alert>}{!items && !error ? <Loading label="Loading submissions…" /> : items?.length ? <div className="table-card"><table><thead><tr><th>Student</th><th>Quiz</th><th>Submitted</th><th>Status</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div className="student-cell"><span className="avatar avatar--small">{item.studentName.split(' ').map((part) => part[0]).join('')}</span><strong>{item.studentName}</strong></div></td><td>{item.quizTitle}</td><td>{new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(item.submittedAt))}</td><td><StatusBadge status={item.status} /></td><td><Link className="button button--secondary button--small" to={`/teacher/submissions/${item.id}`}>Open review <Icon name="arrow" size={15} /></Link></td></tr>)}</tbody></table></div> : <EmptyState icon="users" title="No submissions yet" message="Student submissions will appear here after a quiz is completed." />}</div>
}

export function SubmissionReviewPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { showToast } = useToast(); const [item, setItem] = useState(null); const [review, setReview] = useState({ mark: '', feedback: '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { api.getSubmission(id).then((result) => { setItem(result); setReview({ mark: result.mark || '', feedback: result.feedback || '' }) }).catch((cause) => setError(cause.message)) }, [id])
  const save = async () => { if (review.mark !== '' && (Number(review.mark) < 0 || Number(review.mark) > 100)) { setError('Mark must be between 0 and 100.'); return }; setSaving(true); setError(''); try { const result = await api.reviewSubmission(id, review); setItem(result); showToast('Review saved successfully.') } catch (cause) { setError(cause.message) } finally { setSaving(false) } }
  if (error && !item) return <div className="page page--narrow"><Alert>{error}</Alert></div>
  if (!item) return <div className="page"><Loading label="Opening submission…" /></div>
  return <div className="page page--narrow"><button className="back-link" onClick={() => navigate('/teacher/submissions')}>← Back to submissions</button><PageHeader eyebrow="Submission review" title={item.studentName} description={`${item.quizTitle} · Submitted ${new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(item.submittedAt))}`} actions={<StatusBadge status={item.status} />} />{error && <Alert>{error}</Alert>}<section className="answers-review"><h2>Transcribed answers</h2>{item.answers.map((answer, index) => <article key={answer.questionId}><span>Question {index + 1}</span><h3 lang="si">{answer.question}</h3><div className="answer-transcript"><Icon name="file" size={18} /><p lang="si">{answer.transcript}</p></div></article>)}</section><section className="form-card"><h2>Mark & feedback</h2><div className="field field--mark"><label htmlFor="mark">Mark <span>out of 100</span></label><div><input id="mark" type="number" min="0" max="100" value={review.mark} onChange={(e) => setReview({ ...review, mark: e.target.value })} /><span>/ 100</span></div></div><div className="field"><label htmlFor="feedback">Feedback</label><textarea id="feedback" rows="5" value={review.feedback} onChange={(e) => setReview({ ...review, feedback: e.target.value })} placeholder="Add clear, constructive feedback for the student…" /></div><div className="button-row button-row--end"><button className="button button--primary" onClick={save} disabled={saving}>{saving ? <><span className="spinner spinner--small" /> Saving…</> : <><Icon name="check" size={17} /> Save review</>}</button></div></section></div>
}
